oslc-op/oslc-specs

- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
* URLs for the WD
* Pin the ReSpec version via JSDelivr
* add 'label' for ReSpec
> Spec template fixes for RM

- specs/query/oslc-query.html
With the config specified in #105
> Reformat OSLC Query spec

- specs/am/architecture-management-vocab.html
- specs/core/actions.html
- specs/ems/estimation-measurement-vocab.html
- specs/qm/quality-management-vocab.html
- specs/recon/reconciliation-vocab.html
As well as the malforned `wgPublicList` attribute. See #109.
> Remove wgPatentURI attr

- specs/cm/change-mgt-shapes.ttl
- specs/cm/change-mgt-spec.html
- specs/cm/change-mgt-vocab.html
- specs/cm/change-mgt-vocab.ttl
This PR is identical to https://github.com/oslc-op/oslc-specs/pull/121 but is just one relevant commit cherry-picked to a clean branch made from HEAD.
> CM PSD03 fixes for OASIS

- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
> resolves #224

- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
> resolves #222

- specs/rm/requirements-management-spec.html
> resolves #223

- specs/core/attachments.html
> Remove the extra ReSpec properties

- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
This a PR to shape up the working draft. You will be able to review its rendered version once again after merging and there will be a separate PR to promote it to a PSD. 
NB! I did reformatting, you can review individual commits to be able to make sense of the PR.
Fixes #247
> QM WD fixes for PSD 02

- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
> Normative changes to the intro for QM

- specs/asset/asset-management-spec.html
- specs/recon/recon-resource-def.txt
- specs/recon/reconciliation-spec.html
- specs/recon/reconciliation-vocab-2-0.html
quotes shall be straight, this is the PR to fix the rest of the specs #246 did not fix due to the scope
> :hammer_and_wrench: Fix other conformance declarations

- specs/qm/quality-management-spec.html
> Revert a weakened req. on Query support

- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
Closes #256; closes #92.
---
[**EPIC**](https://github.com/oslc-op/oslc-specs/issues/235)
> Fixes before for promoting QM to PSD 

- tools/ShapeChecker/src/main/java/net/open_services/scheck/shapechecker/HttpHandler.java
> Honor the exclude flag for non-RDF links like seeAlso

- specs/query/oslc-query.html
> Update Query to use ReSpec 2.1.13

- specs/query/oslc-query.html
> Fix Query spec ReSpec properties

- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
> QM WD03 (first draft towards PS)

- .circleci/config.yml
- specs/am/architecture-management-shapes.ttl
- specs/am/architecture-management-spec.html
- specs/am/architecture-management-vocab.html
- specs/am/architecture-management-vocab.ttl
- specs/core/actions.html
- specs/core/attachments.html
- specs/core/config.js
- specs/core/core-vocab.html
- specs/core/dialogs.html
- specs/core/discovery.html
- specs/core/oslc-core.html
- specs/core/resource-preview.html
- specs/core/resource-shape.html
- specs/core/vocab/core-vocab.ttl
- tools/ShapeChecker/.gitignore
- tools/ShapeChecker/FindBugsExclude.xml
- tools/ShapeChecker/check-am.sh
- tools/ShapeChecker/check-cm.sh
- tools/ShapeChecker/check-core.sh
- tools/ShapeChecker/check-rm.sh
- tools/ShapeChecker/src/main/java/net/open_services/scheck/shapechecker/HttpHandler.java
Updated Architecture Management spect for version 3.0 to include common link type properties from the jazz.net DM namespace. This provides the missing properties that connect architecture management resources to the other OSLC lifecycle management domain specifications.
> AM v3.0 PSD01 changes

- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
> Preparing for RM V2.1 PS01

- .circleci/config.yml
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
* Fixed problems from respec
* ran and fixed problems from prettier --check specs/rm/
* ran prettier --write specs/rm/
* Update the <script> at start of both html documents, to match QM.
> RM - Prettier and Respec

- specs/perfmon/performance-monitoring-vocab.ttl
> Fix bad prefix definition in perfmon

- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
resolves #350
I build this pull request on the previous pull request https://github.com/oslc-op/oslc-specs/pull/359 to avoid conflicts. But now see that it was not necessary. The changes are completely independent. But anyway, maybe they can approved at the same time, since they are quite small.
> resolving issue #350

- specs/qm/quality-management-shapes.html
- specs/qm/quality-management-shapes.ttl
- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.ttl
Closes #368; also resolves #355
> Split the QM vocab

- specs/cm/change-mgt-shapes.ttl
- specs/cm/change-mgt-vocab.ttl
- specs/core/core-shapes.ttl
- specs/core/core-vocab.ttl
These will be filled in later.
Fixes #381
> Commented out issued properties

- specs/cm/change-mgt-shapes.ttl
- specs/cm/change-mgt-vocab.ttl
- specs/core/core-shapes.ttl
- specs/core/core-vocab.ttl
- specs/qm/quality-management-shapes.ttl
- specs/qm/quality-management-vocab.ttl
- tools/ShapeChecker/check-am.sh
- tools/ShapeChecker/check-cm.sh
- tools/ShapeChecker/check-core.sh
- tools/ShapeChecker/check-main.sh
- tools/ShapeChecker/check-qm.sh
- tools/ShapeChecker/check-rm.sh
> Update QM shape prefixes

- tools/ShapeChecker/check-am.sh
- tools/ShapeChecker/check-cm.sh
- tools/ShapeChecker/check-core.sh
- tools/ShapeChecker/check-qm.sh
- tools/ShapeChecker/check-rm.sh
In relation to #387
Signed-off-by: Andrew Berezovskyi <andriib@kth.se>
> Suppress unusedVocabulary in SC

- tools/ShapeChecker/README.md
Describes newer options
Use the same ordering and case as the code
> Update README.md to be in sync with the code

- specs/qm/quality-management-shapes.html
- specs/qm/quality-management-vocab.html
> A small bug fix for the meta-content of QM

- specs/rm/requirements-management-shapes.html
- specs/rm/requirements-management-shapes.ttl
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
1 update of base url for shapes to be
2. http://open-services.net/ns/rm/shapes/2.1
> update to latest rspec version

- specs/rm/requirements-management-shapes.html
- specs/rm/requirements-management-shapes.ttl
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
- specs/rm/requirements-management-vocab.ttl
> solves #386 I hope.

- specs/rm/requirements-management-shapes.html
- specs/rm/requirements-management-shapes.ttl
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
- specs/rm/requirements-management-vocab.ttl
This is an attempt at https://github.com/oslc-op/oslc-specs/issues/374.
But I can't get the shapes to be visible in hte shapes.html document.
@berezovskyi @ndjc tips?
> WIP - Split Vocab and Shapes.

- specs/rm/requirements-management-spec.html
resolves #394
THis is according to the following entries. 
https://docs.oasis-open-projects.org/oslc-op/rm/v2.1/psd02/
https://docs.oasis-open.org/oslc-domains/oslc-rm/v2.1/cs01/
https://docs.oasis-open.org/oslc-domains/oslc-rm/v2.1/csprd01/
> resolves #394

- specs/qm/quality-management-shapes.html
- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
Also reduce hr and table borders to 1px in the process. Closes #390
> Fix W3C validation errors in QM

- specs/rm/requirements-management-shapes.html
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
Closes #402
I made to changes that I would like @berezovskyi  to check.  I remove (a) bgcolor & (b) font
> Closes #402

- tools/ShapeChecker/check-qm.sh
Will fix as part of the COS01 prep, this PR is to stop breaking the build.
> Disable QM shape checks

- specs/core/discovery.html
Closes #157 
**TODO**
- https://jazz.net/wiki/bin/view/Main/RootServicesSpec
- https://tools.ietf.org/html/rfc8615#section-3.1
> Add a well-known URIs section

- specs/core/dialogs.html
> Add CSP reference

- specs/core/oslc-core.html
> Add CORS reference

- specs/core/oslc-core.html
> Add ABNF grammar and a conf clause

- tools/ShapeChecker/FindBugsExclude.xml
- tools/ShapeChecker/src/main/java/net/open_services/scheck/util/CheckIndex.java
- tools/ShapeChecker/src/main/java/net/open_services/scheck/util/PrintVocabs.java
The changes do not impact OSLC specs - a new tool was added to verify the namespace index for jazz.net/ns.
> Add utility to check jazz.net namespace index file

- specs/config/config-resources.html
- specs/config/config-shapes.ttl
Fix reference to shape, and add conformance clause styling.
Fixes #499
> Fix reference to Activity shape; add conformance clause styling

- tools/ShapeChecker/src/main/java/net/open_services/scheck/shapechecker/HttpHandler.java
- tools/ShapeChecker/src/main/java/net/open_services/scheck/util/CheckIndex.java
Add a check for the vocabulary URI itself, and add some debugging code
> Add some more checks to the jazz.net index check utility

- .circleci/config.yml
- specs/trs/guidance.html
- specs/trs/tracked-resource-set-vocab.html
- specs/trs/tracked-resource-set.html
- specs/trs/trs-shapes.ttl
- specs/trs/trs-vocab.ttl
- tools/ShapeChecker/scripts/check-trs.sh
I have incorporated feedback as specified in PR #509.
I believe this draft is now ready to be polished into a project spec.
> Trs30 draft2

- specs/core/config.js
- specs/core/core-shapes.ttl
- specs/core/core-vocab.ttl
- specs/core/oslc-core.html
- specs/core/resource-shape.html
See #478 
See also https://github.com/oasis-open-projects/administration/issues/21 and https://lists.oasis-open-projects.org/g/oslc-op-pgb/topic/formal_notice_of_intent_to/81802606
> Update Core PS02 release metadata

- specs/cm/change-mgt-shapes.html
- specs/cm/change-mgt-shapes.ttl
- specs/cm/change-mgt-spec.html
- specs/cm/change-mgt-vocab.html
- specs/cm/change-mgt-vocab.ttl
See https://issues.oasis-open.org/browse/TCADMIN-3996 for OS publication progress
See https://github.com/oasis-tcs/tab-respec/pull/51 for the list of changes to the templates
> Prepare a final CM OS package

- specs/rm/requirements-management-shapes.html
- specs/rm/requirements-management-shapes.ttl
- specs/rm/requirements-management-spec.html
- specs/rm/requirements-management-vocab.html
- specs/rm/requirements-management-vocab.ttl
See https://issues.oasis-open.org/browse/TCADMIN-4019
> Prepare RM 2.1 OS package

- specs/am/architecture-management-shapes.html
- specs/am/architecture-management-shapes.ttl
- specs/am/architecture-management-spec.html
- specs/am/architecture-management-vocab.html
- specs/am/architecture-management-vocab.ttl
> Updates for AM PS01

- specs/config/README.md
- specs/config/config-resources.html
- specs/config/config-shapes.ttl
- specs/config/config-vocab.html
- specs/config/config-vocab.ttl
- specs/config/oslc-config-mgt.html
- specs/config/versioned-resources.html
- tools/ShapeChecker/README.md
Please review before I create the zip files and send out the notice of intent to publish to the PGB.
> Updates to prepare for publishing Config PSD01

- .github/workflows/linter.yaml
- specs/config/config-resources.html
- specs/config/config-shapes.ttl
- specs/config/config-vocab.html
- specs/config/config-vocab.ttl
- specs/config/oslc-config-mgt.html
- specs/config/versioned-resources.html
The purpose of this PS is get a stable document published that implementors can start using before we have resolved all the open issues and have a COS ready.
resolves: #553, #414, #543, #547
> Publish Config v1.0 PS01

- specs/qm/quality-management-shapes.html
- specs/qm/quality-management-shapes.ttl
- specs/qm/quality-management-spec.html
- specs/qm/quality-management-vocab.html
- specs/qm/quality-management-vocab.ttl
Please note the change of the `oslc_qm` prefix from `http://open-services.net/ns/core/qm#` to `http://open-services.net/ns/qm#`. Everywhere we are using `http://open-services.net/ns/qm#`:
<details>
<summary>Instances of http://open-services.net/ns/qm#</summary>
```
❯ rg "http://open-services.net/ns/qm\#"
templates/domain-name-vocab.html
210:          <li>oslc_qm : <code>http://open-services.net/ns/qm#</code> [[OSLCQM]]</li>
templates/domain-name-spec.html
261:<li>oslc_qm : <code>http://open-services.net/ns/qm#</code> [[OSLCQM]]</li>
specs/cm/change-mgt-vocab.html
229:          <li>oslc_qm : <code>http://open-services.net/ns/qm#</code> [[OSLCQM]]</li>
specs/qm/quality-management-spec.html
209:        namespaces: [{ href: "http://open-services.net/ns/qm#", prefix: "oslc_qm" }],
562: …
```
> QM OS edits

- tools/ShapeChecker/scripts/check-config.sh
- tools/ShapeChecker/src/main/java/net/open_services/scheck/shapechecker/HttpHandler.java
- tools/ShapeChecker/src/main/resources/location-mapping.ttl
- tools/ShapeChecker/src/main/resources/vocabs/foaf.ttl
- tools/ShapeChecker/src/main/resources/vocabs/ldp.ttl
This should fix the inaccessibility of the older vocabs.
> Map foaf: and ldp: prefixes to local files

- specs/cm/change-mgt-shapes.html
- specs/cm/change-mgt-shapes.ttl
- specs/cm/change-mgt-spec.html
- specs/cm/change-mgt-vocab.html
- specs/cm/change-mgt-vocab.ttl
- specs/config/config-shapes.ttl
- specs/config/config-vocab.ttl
Added the properties to the vocabulary and shapes.
> Added the missing oslc_qm link properties

- specs/ldm/ldm-service.yaml
- specs/ldm/link-discovery-management-spec.html
Changed publish date to correspond to PGB vote.
> Publish ldm v1.0 psd01
